# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  docker-build:
    runs-on: ubuntu-latest # This tells GitHub Actions to run this job on a temporary Ubuntu Linux machine.
    needs: build # This means "Do not start docker-build until the build job passes."

    steps: # This is the list of tasks that will run inside the docker-build job.
      - name: Checkout repository # This is the display name of the step shown in the GitHub Actions logs.
        uses: actions/checkout@v4 # This downloads your repository code into the GitHub Actions runner so Docker can access the Dockerfile and project files.

      - name: Build Docker image # This is the display name of the Docker build step in the GitHub Actions logs.
        run: docker build -t gha-node-ci-cd-practice . # This runs the Docker build command, names the image gha-node-ci-cd-practice, and uses the current repository folder as the build context.   
